name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-13
      with:
        args: test
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-13
      with:
        args: distZip
    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
        name: distribution
        path: build/distributions/yap.zip
